name: Build and Deploy Spring Boot (Java 21) to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "NVS"
          slot-name: "Production"
          package: "target/nvs-stage-management-0.0.1-SNAPSHOT.jar"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # nếu bạn muốn quay về dùng publish profile
